Make `frozenset(empty_iterable)` return a singleton.
RustPython/RustPython pull request #2715
Opened 2021-06-17 16:33 UTC by DimitrisJim

This covers creating an empty frozenset through Python code. Modules implemented in rust could still use `from_iter` (as `ssl` does) and end up with an empty frozenset which isn't the singleton.

2021-06-17 17:00 UTC, DimitrisJim commented
clippy appears to be complaining for something unrelated which I can't replicate (even after updating to `0.1.53` which was released earlied today).

2021-06-22 18:34 UTC, DimitrisJim commented on vm/src/builtins/set.rs
> +            let iterable = if cls.is(&vm.ctx.types.frozenset_type) {
Though I've seen this used in other `__new__`'s it seems superfluous. Wouldn't:

```rust
let iterable = match iterable.downcast_exact::<Self>(vm) {
    Ok(fs) => return Ok(fs),
    Err(iterable) => iterable,
};
```

suffice in only allowing `frozenset` instances (and not subclasses of `frozenset`!) to return immediately?

2021-07-07 15:00 UTC, youknowone approved these changes

2021-07-07 15:02 UTC, youknowone requested changes
By this change, `#[allow(dead_code)]` of `from_iter`will be useless. Could you remove the annotation too?

2021-07-11 22:10 UTC, DimitrisJim commented
@youknowone Removed that annotation (left the comment though, it seems helpful to have it around).

2021-07-12 07:07 UTC, youknowone approved these changes
It looks great! Thank you!

2021-07-12 07:07 UTC, merged