add ` time.time_ns()`  function
RustPython/RustPython pull request #2880
Opened 2021-08-14 06:48 UTC by Regexp96

I add `time.time_ns()` 
` time_ns`  is to get the time in nanoseconds since the epoch

2021-08-14 06:51 UTC, youknowone commented on vm/src/stdlib/time_module.rs
> +#[cfg(any(not(target_arch = "wasm32"), target_os = "wasi"))]
i didn't know wasm has confusing discussion about it.
https://stackoverflow.com/questions/6002808/is-there-any-way-to-get-current-time-in-nanoseconds-using-javascript

2021-08-14 06:52 UTC, youknowone requested changes

2021-08-14 06:52 UTC, youknowone commented on vm/src/stdlib/time_module.rs
> +pub fn get_time_ns() -> u64 {
In general, we never want the interpreter is crashed by python code. The correct signature of failible function is like this:
```suggestion
pub fn get_time_ns() -> PyResult<u64> {
```

2021-08-14 07:00 UTC, youknowone requested changes

2021-08-14 07:00 UTC, youknowone commented on vm/src/stdlib/time_module.rs
> +        Err(err) => panic!("Time error: {:?}", err),
```suggestion
        Err(err) => unsafe { std::hint::unreachable_unchecked() }, // guaranted to be not to be happen with now() + UNIX_EPOCH
```

this hint will remove the branch itself for release build

2021-08-14 07:04 UTC, youknowone commented on vm/src/stdlib/time_module.rs
> +        "time_ns" => named_function!(ctx,time,time_ns),
`extend_module!` macro will be helpful to quarantine this function from wasm

2021-08-14 13:11 UTC, youknowone commented
@Regexp96 it looks good, but there is a conflict by recent merge. would you rebase it once again?

2021-08-14 15:06 UTC, youknowone approved these changes

2021-08-14 15:07 UTC, merged

2021-08-15 02:41 UTC, coolreader18 commented
Ah, should've commented earlier, but isn't it possible for `::now() < UNIX_EPOCH` if someone sets the system time to before 1970? I'd think it should just return a negative number in that case (which is definitely possible, you can just do `Err(e) => e.duration()`), though I haven't looked at what cpython does