Implement `array::_array_reconstructor`
RustPython/RustPython pull request #2937
Opened 2021-08-22 11:42 UTC by whjpji

2021-08-25 09:27 UTC, whjpji commented
Hi, @coolreader18, I'm working with the UTF32 encodings/decodings. There are already some enc/dec functions in [`Lib/_pycodecs.py`](https://github.com/RustPython/RustPython/blob/main/Lib/_pycodecs.py).

There is a comment says that it comes from PyPy, but I cannot find the source in PyPy's code base, but only find [this file](https://foss.heptapod.net/pypy/pypy/-/blob/branch/default/pypy/module/_codecs/interp_codecs.py). It is very different from `_pycodecs.py`.

Did you remember where the `_pycodecs.py` come from? I might quickly add the enc/dec for UTF32, and maybe rewrite them in Rust in the next PR.

2021-08-29 03:27 UTC, whjpji commented
@youknowone No problem. Let me resolve the conflicting files first.

2021-08-29 22:39 UTC, coolreader18 commented
One last thing - could you separate this into 2 commits? One with reformatting `array.rs` to be `mod array { ... }`, the other with the changes you made for `_array_reconstructor`? Hopefully that shouldn't be too hard :grimacing:

2021-08-30 00:35 UTC, whjpji commented
Oh, sad! The indents in marcos of the first commit is not correct, let me fix it.

2021-08-30 07:23 UTC, youknowone requested changes

2021-08-30 07:36 UTC, youknowone commented on vm/src/stdlib/array.rs
> +                eprintln!("utf16: {:?}", s);
these `eprintln`s look like debug prints probably not inteded to be included in final PR

2021-08-30 07:37 UTC, youknowone commented
I left 2 more comments and other parts looks good.

2021-08-30 14:48 UTC, youknowone approved these changes

2021-08-30 15:03 UTC, merged