Check that all abstract methods are implemented prior to instantiation
RustPython/RustPython pull request #3434
Opened 2021-11-14 01:31 UTC by chrismoradi

Raises a `TypeError` if any abstract methods are not implemented when you try to instantiate a class.

E.g.,
```python
>>>>> from collections.abc import Iterable
>>>>> class I(Iterable):
.....     pass
.....
>>>>> i = I()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: You must implement the abstract methods
```

CPython has a more descriptive error message:

```python
TypeError: Can't instantiate abstract class I with abstract method __iter__
```

After spending a ton of time, I was unable to figure out how to retrieve the names of the abstract methods. I would love some feedback to fix this. I'm pretty confident that the implementation could be improved substantially, but I'm very new to Rust and unsure how to fix this.

2021-11-15 16:31 UTC, youknowone requested changes
looks great, thanks!

2021-11-15 18:10 UTC, chrismoradi commented on vm/src/builtins/object.rs
> +            if let Some(iter) = vm.get_method(abs_methods, "__len__") {
Awesome! Thanks so much for this help.

2021-11-15 18:11 UTC, chrismoradi commented on vm/src/builtins/object.rs
> +                if unimplemented_abstract_method_count > &BigInt::from(0) {
After making the changes to `obj_len_opt` I now get back a `usize` so I don't think I need this, but lmk if there's a more idiomatic way to implement this.

2021-11-15 18:38 UTC, youknowone approved these changes

2021-11-15 19:31 UTC, chrismoradi commented
@youknowone, I see that the Windows unittests are failing, but it seems unrelated to the changes I made (checked some and they're PermissionErrors). Are these tests known to be broken/flaky or is this something I should look into fixing before this PR is merged?

2021-11-15 19:32 UTC, youknowone commented
I think I made mistake for recent merges. Let me check it. Sorry for make troubles

2021-11-15 19:36 UTC, chrismoradi commented
Thank you! just wanted to make sure I didn't break anything.

2021-11-23 00:02 UTC, chrismoradi commented
@youknowone, looks like the tests are passing again. Can this be merged?

2021-11-23 00:17 UTC, merged

2021-11-23 00:17 UTC, coolreader18 commented
Thanks for contributing!