refactor: implement repr_helper for collections
RustPython/RustPython pull request #3471
Opened 2021-11-28 07:30 UTC by TeamTamoad

Implement an helper functions to for repr function of the collections including list, tuple, set and deque.

2021-11-29 10:21 UTC, youknowone requested changes

2021-11-29 10:21 UTC, youknowone commented on vm/src/utils.rs
> +    brackets: [char; 2],
This variable is always used only for each char, but never as array. If we change this to `prefix: &str, suffix: &str`, we can handle more cases. For example, `deque` is now formatted again using maxlen. But if we just pass suffix string, we can pass right bracket and maxlen at same time.

2021-11-29 11:47 UTC, TeamTamoad commented
Those changes are really good ideas. I'll do that.
Btw, do you have any idea why my last changes don't pass the test in time ?

2021-11-30 05:36 UTC, youknowone commented
I have no idea yet. But becasue it failed again exceeding the time limit, it seems this changes made something.

2022-01-17 20:00 UTC, fanninpm commented
> Btw, do you have any idea why my last changes don't pass the test in time ?

Try running the following command:

```text
cargo run --release --features ssl,jit -- -m test -v
```

2022-01-19 16:55 UTC, fanninpm commented
[It was hanging in the snippets.](https://github.com/RustPython/RustPython/runs/4857239926) To diagnose,

1. Build RustPython in release mode (with the features normally used for testing): `cargo build --release --features ssl,jit`
2. Navigate to the `extra_tests` directory and install `pytest` into a virtual environment. (e.g., `cd extra_tests && pipenv install --python 3.9`)
3. Run pytest on the `extra_tests` directory. (e.g., `pipenv run pytest -v`)

2022-03-20 15:25 UTC, pwnorbitals commented
how far are we from completion here @TeamTamoad ? :)

2022-03-20 17:58 UTC, TeamTamoad commented
Sorry for an late update. I'm super busy with life and college right now.
The hanging problem is cause by this snippet in file `extra_tests/snippets/stdlib_collections.py`
```python
# Test that calling an evil __repr__ can't hang deque
class BadRepr:
    def __repr__(self):
        self.d.pop()
        return ''

b = BadRepr()
d = deque([1, b, 2])
b.d = d
repr(d)
```
It should be fixed now

2022-03-24 22:20 UTC, youknowone approved these changes
great! thank you for the long time effort!

2022-03-24 22:21 UTC, merged