Fix test_long::test_huge_rshift
RustPython/RustPython pull request #3580
Opened 2022-03-18 14:39 UTC by hrchu

A BigUint is represented as a vector of BigDigits and it seems that in Rust no allocations can have a size larger than `isize::MAX`. `usize::MAX` is sufficient for shifting purposes here.

2022-03-20 14:50 UTC, youknowone commented
I didn't check what's happening in `extra_tests/snippets/ints.py`, but `inner_shift` is processing both lshift and rshift. So maybe this test fails for lshift, which have to raise overflow error.

2022-03-20 14:50 UTC, youknowone commented
I didn't check what's happening in `extra_tests/snippets/ints.py`, but `inner_shift` is processing both lshift and rshift. So maybe this test fails for lshift, which have to raise overflow error.

2022-03-21 01:45 UTC, hrchu commented
ok, I'll check it later.
I have some issues with my M1/arm64 environment 🥲

2022-03-21 08:15 UTC, hrchu commented
Yes, you are right. I can confirm that the fail case is `assert_raises(OverflowError, lambda: 1 << 10 ** 100000)`

2022-04-18 13:39 UTC, youknowone commented
@hrchu did you find the way to distinguish rshift and lshift?

2022-04-19 13:14 UTC, hrchu commented
Yes we need to check "number is too large"  if the shift op is ""<<"".
The problem is I need two versions of `inner_shift` with different behavior. Thats stupid.
I still thinking about how to make this more gracefully. Any ideas?
 

![image](https://user-images.githubusercontent.com/3183314/164011120-338b2d4d-116c-4d67-ad2b-5fbb074e5047.png)

2022-04-20 08:23 UTC, youknowone commented
Will you push the new version to discuss more? I think we don't have much choice. Maybe we can make another small function for shared behavior, but I think having `inner_lshift` and `inner_rshit` is hard to avoid without a clever idea.

2022-04-24 13:52 UTC, hrchu commented
@youknowone pushed. have a look plz 🙏

2022-04-24 15:01 UTC, youknowone requested changes

2022-04-25 13:51 UTC, hrchu commented on vm/src/builtins/int.rs
> +        let int2 = int2.min(&BigInt::from(usize::MAX)).to_usize().unwrap();
Absolutely! I've thought about it but that means we still have duplicate code on our closures (and it's a little bit long lol)

```
            |a: &BigInt, vm: &VirtualMachine| {
                a.to_usize().ok_or_else(|| {
                    vm.new_overflow_error("the number is too large to convert to int".to_owned())
                }).unwrap();
            };

           |a: &BigInt, vm: &VirtualMachine| a.min(&BigInt::from(usize::MAX)).to_usize().unwrap();
``` 

Is that work for you? Or should we consider any way to reuse these closures instead?

2022-04-25 15:24 UTC, youknowone commented on vm/src/builtins/int.rs
> +        let int2 = int2.min(&BigInt::from(usize::MAX)).to_usize().unwrap();
If you mean `.to_usize()` part, I think thats repeat by their requirements. So it is ok.

2022-04-28 20:47 UTC, youknowone reviewed
You were talking about 2 duplicated code patterns. I thought you were asking about duplication between them. Now I got it. I think the duplication can be resolved by making them as free functions.

2022-04-28 20:47 UTC, youknowone commented on vm/src/builtins/int.rs
> +    S: Fn(&BigInt) -> usize,
```suggestion
    S: Fn(&BigInt) -> PyResult<usize>,
```
The error has to be propagated out

2022-04-28 20:47 UTC, youknowone commented on vm/src/builtins/int.rs
> +                    },
this part can be a free function and reused in rlshift

2022-05-03 23:28 UTC, youknowone approved these changes
Thank you!

2022-05-03 23:28 UTC, merged

2022-05-04 00:18 UTC, hrchu commented
@youknowone thank you for guidance!