Add `Reduce` method in reverse_iter
RustPython/RustPython pull request #3597
Opened 2022-04-09 11:56 UTC by jeon-yongjun

add `reduce` method to reverse_iter and obliterated the failure that was foreseen by it

2022-04-09 12:33 UTC, youknowone requested changes
This patch also fixed a test  `test_enum::test_unique_composite`. Please remove expectedFailure decorator from the test.

2022-04-09 12:33 UTC, youknowone commented on vm/src/builtins/dict.rs
> +                        .map(|(key, value)| ($result_fn)(vm, key, value))
here is a clippy error.

2022-04-10 04:26 UTC, Snowapril commented
> This patch also fixed a test `test_enum::test_unique_composite`. Please remove expectedFailure decorator from the test.

It seems temporary error. we cant replicate our environment(window, ubuntu).
We add `expectedFailure` again and it works now 😊

2022-04-10 04:32 UTC, youknowone approved these changes
Looks good, thank you for contributing!

2022-04-10 04:32 UTC, merged