implement aiter
RustPython/RustPython pull request #3646
Opened 2022-04-19 18:21 UTC by sum12

the caller is expected to make sure that the passed in object does in
fact supports the protocol

relates #3609

2022-04-19 19:04 UTC, youknowone commented
Will you add a simple test if it actually calls `__aiter__` from the object?
When possible, we prefer to add tests from CPython's test, but if not possible.
Otherwise, adding a file to `extra_tests/snipepts` will be enough.
Then our CI will ensure their behavior is same in both CPython and RustPython.

2022-04-19 20:08 UTC, fanninpm commented
> Will you add a simple test if it actually calls `__aiter__` from the object?
> When possible, we prefer to add tests from CPython's test, but if not possible.
> Otherwise, adding a file to `extra_tests/snipepts` will be enough.
> Then our CI will ensure their behavior is same in both CPython and RustPython.

I think we can just update our copy of [`test_asyncgen.py`](https://github.com/RustPython/RustPython/blob/787d9d0bbb59da79fa061b870c234314877ff9b0/Lib/test/test_asyncgen.py) to the version from [CPython 3.10](https://github.com/python/cpython/blob/3.10/Lib/test/test_asyncgen.py).

2022-04-20 08:30 UTC, youknowone commented
I think you already added tests from the CPython, but here is a guideline if you want to know the regular way: https://github.com/RustPython/RustPython/wiki/How-to-update-test-files

2022-04-20 21:30 UTC, youknowone requested changes
looks good for codes. I have one more request for the commit message. For the commit for test update (https://github.com/RustPython/RustPython/pull/3646/commits/64cb090f96a130a4e18b6ffb0ac8ec9ccdea80e1), please leave the updated source of the CPython version. That will be very useful for future contributor of the file. Because `git log Lib/test/test_asyncgen.py` will show how it is changed by the history just by looking for the log.

2022-04-21 07:27 UTC, youknowone commented
Because #3647 updated the test file, rebase will be enough

2022-04-22 02:33 UTC, youknowone approved these changes
looks good, thank you!

2022-04-22 02:33 UTC, merged

2022-04-22 02:35 UTC, youknowone commented
@sum12 If you want, converting it to use slots would be also an approachable task