Changed PyAttributes type to IndexMap
RustPython/RustPython pull request #3660
Opened 2022-04-24 15:33 UTC by djrmarques

Hello!

This is my first pull request, I am very eager to star contributing to this project. 

I believe I have addressed #3607, at least all the tests seem to pass since I made the changes.

Thank you :)

2022-04-24 18:03 UTC, youknowone requested changes

2022-04-24 18:03 UTC, youknowone commented on vm/src/builtins/type.rs
>  /// TODO: class attributes should maintain insertion order (use IndexMap here)
would you also fix the comment here?

2022-04-24 18:04 UTC, youknowone commented
It looks good in general. I left a few comments not about code

2022-04-24 18:49 UTC, djrmarques commented
Hope it's ok now :)

2022-04-25 00:24 UTC, coolreader18 commented on vm/src/builtins/type.rs
> +            .drain(..)
I know `drain()` was already here, but this can actually just be `.into_iter()`.

2022-04-25 04:33 UTC, youknowone approved these changes

2022-04-25 06:04 UTC, merged

2022-04-25 06:06 UTC, youknowone commented
I am going to merge it now because drain() is out of boundary of this PR and we should click the run CI button manually for the first contributors.

@djrmarques Thank you for contributing. please feel free to open another PR to chain drain() if you want to do.

2022-04-25 06:40 UTC, djrmarques commented
Will do it later probably ☺️