Fixed `test_bytearray_translate` Error
RustPython/RustPython pull request #3730
Opened 2022-05-21 08:10 UTC by Lithium07z

FileName: `test_builtin.py`
FunctionName: `test_bytearray_translate`
Error: RustPython was throwing wrong `Error`, RustPython was throwing `TypeError`

2022-05-21 10:01 UTC, youknowone requested changes

2022-05-22 01:07 UTC, fanninpm commented on vm/src/bytesinner.rs
> +            |v: PyObjectRef| {
@Lithium07z If you're working in VSCode/Codium, rust-analyzer can show you the types that Rust can infer.

2022-05-22 01:24 UTC, Lithium07z commented on vm/src/bytesinner.rs
> +            |v: PyObjectRef| {
!! thank you so much XD

2022-05-22 01:57 UTC, youknowone approved these changes
thank you for contributing!

2022-05-22 01:57 UTC, merged