Update staticmethod.rs
RustPython/RustPython pull request #3742
Opened 2022-05-22 04:39 UTC by HyunP-dev

2022-05-22 04:41 UTC, youknowone requested changes
running `cargo fmt --all` will fix the fmt failure

2022-05-22 04:41 UTC, youknowone commented on vm/src/builtins/staticmethod.rs
> +        // zelf.as_object().set_attr("__format__", args.get_attr("__format__", vm)?, vm);
```suggestion
```

2022-05-22 05:13 UTC, youknowone requested changes

2022-05-22 05:13 UTC, youknowone commented on vm/src/builtins/staticmethod.rs
> +        // zelf.as_object().set_attr("__format__", args.get_attr("__format__", vm)?, vm);
```suggestion
```

2022-05-22 07:05 UTC, Snowapril commented
`expectedFailure` above the `test_decorators::test_staticmethod` need to be removed.

And it seems `test_reprlib::test_descriptors` codes are outdated and it causes the FAIL. 
You need to update `Lib/test/test_reprlib.py` up to python 3.10 (ref https://github.com/python/cpython/blob/3.10/Lib/test/test_reprlib.py#L195-L208)
Or add `expectedFailure` on that test and add separate PR for updating it.

2022-05-26 22:45 UTC, fanninpm commented
> Or add `expectedFailure` on that test and add separate PR for updating it.

Now that #3747 has been merged, can this be rebased on a fresh copy of the `main` branch?

2022-08-07 05:53 UTC, youknowone commented on vm/src/builtins/staticmethod.rs
> +            .set_attr("__doc__", args.get_attr("__doc__", vm)?, vm)?;
this is not a fix. object is replaced, not doc.

2022-08-07 06:22 UTC, youknowone approved these changes
no behavior changed but harmless and preparation for next step

2022-08-07 06:22 UTC, merged