add getformat
RustPython/RustPython pull request #3774
Opened 2022-06-11 07:41 UTC by Miragecore

2022-06-11 11:08 UTC, youknowone requested changes

2022-06-11 11:08 UTC, youknowone commented on vm/src/builtins/float.rs
> +            return Err(vm.new_value_error(format!(
Please check this clippy advice

2022-06-11 11:38 UTC, Miragecore commented
Because of this issue https://github.com/rust-lang/rust-clippy/issues/8527,
I can't check this on my local.

2022-06-11 11:45 UTC, Miragecore commented
Because of this issue https://github.com/rust-lang/rust-clippy/issues/8527, I can't check this on my local.

2022-06-12 06:38 UTC, youknowone approved these changes
Thank you for contributing!

2022-06-12 06:38 UTC, merged