Fix itertools chain
RustPython/RustPython pull request #3788
Opened 2022-06-14 07:12 UTC by rng-dynamics

Fix #3787

2022-06-14 14:38 UTC, fanninpm commented on vm/src/stdlib/itertools.rs
>                  }
📎 "_It looks like you're `match`ing variants of an `Option`. Would you like help?_" 📎

```rust
if let Some(source) = zelf.source.read().clone() {
    loop {
        if let Some(active) = zelf.active.read().clone() {
            match active.next(vm) {
                Ok(PyIterReturn::Return(ok)) => {
                    return Ok(PyIterReturn::Return(ok));
                }
                Ok(PyIterReturn::StopIteration(_)) => {
                    *zelf.active.write() = None;
                }
                Err(err) => {
                    return Err(err);
                }
            }
        } else {
            match source.next(vm) {
                Ok(PyIterReturn::Return(ok)) => {
                    *zelf.active.write() = Some(ok.get_iter(vm)?);
                }
                Ok(PyIterReturn::StopIteration(_)) => {
                    return Ok(PyIterReturn::StopIteration(None));
                }
                Err(err) => {
                    return Err(err);
                }
            }
        }
    }
} else {
    Ok(PyIterReturn::StopIteration(None))
}
```

2022-06-14 15:11 UTC, youknowone requested changes
Thank you! The changes looks good.
Do you have more works to do? I wonder what made this marked as draft.

2022-06-14 18:59 UTC, rng-dynamics commented
Thanks for the suggestions. I tried to incorporate them and I tried to reduce the nesting. I also removed the closure which I didn't like that much. Let me know what you think. If you have more suggestions, I'd be happy to hear them.

> Thank you! The changes looks good. Do you have more works to do? I wonder what made this marked as draft.

The main reason was the clippy test which failed.

2022-06-15 02:10 UTC, youknowone approved these changes
Looks good, thank you!

2022-06-15 02:11 UTC, merged

2022-06-15 03:12 UTC, youknowone commented
It fixed the ridiculously slow running of `test_itertools.py`, nice catch and fix!
Now the only slow running is `tee`