added getnewargs() to str.rs
RustPython/RustPython pull request #3811
Opened 2022-06-23 09:25 UTC by zer0who

Added getnewargs() to str.rs and have tested on test_unicode.py(test_getnewargs())

2022-06-23 17:10 UTC, fanninpm commented
#3807 was recently merged, which changes how CI runs the test suites. Can you rebase your branch on a fresh copy of `main`? Once you've done that, feel free to run the following command:

```text
cargo run --release --features ssl,jit -- -m test -j 1 -u all --slowest --fail-env-changed -v test_enum test_pickle test_pickletools test_unicode
```

(Of course, everything after the `-v` flag can be changed out with whatever tests you want. Or none at all, if you have plenty of time to spend.)

2022-06-23 17:27 UTC, youknowone reviewed
Great! you fixed many more than just a single test. Could you please remove `expectedFailure` decorators from other successful tests?

2022-06-28 15:34 UTC, fanninpm requested changes
Some minor cleanup comments, and I think this should be good to go.

2022-06-28 15:34 UTC, fanninpm commented on Lib/test/test_pickle.py
> -    @unittest.expectedFailure
When you delete this, can you also delete the two lines that say `# TODO: RUSTPYTHON, remove when this passes`?

2022-06-28 15:34 UTC, fanninpm commented on Lib/test/test_pickletools.py
> -    @unittest.expectedFailure
When you delete this, can you also delete the two lines that say `# TODO: RUSTPYTHON, remove when this passes`?

2022-06-28 15:34 UTC, fanninpm commented on Lib/test/test_pickletools.py
> -    @unittest.expectedFailure
When you delete this, can you also delete the two lines that say `# TODO: RUSTPYTHON, remove when this passes`?

2022-06-28 15:59 UTC, fanninpm requested changes
I apologize if this wasn't clear, but I meant to say the **entirety** of the lines. Right now these lines are just redundant, and they can go away (along with the extra whitespace).

2022-06-28 16:08 UTC, fanninpm commented
> You mean that delete the test 'functions' which I deleted expectedFailure annotation?

Any lines that now say
```python
def test_function(self):
    super().test_function()
```
are just redundant at this point if they're not annotated with a `@unittest.expectedFailure` or a `@unittest.skip` decorator. They also make it harder to upgrade the test suite in the future.

If a test function has something else other than a call to `super()`, you can leave it be.

2022-06-28 16:11 UTC, zer0who commented
Is this right?

2022-06-28 16:14 UTC, zer0who commented
Thank you, too!!

2022-06-29 17:47 UTC, fanninpm commented
According to the CI, it seems you may have missed a test in `test_pickle.py`. Are you able to replicate what CI is showing?

2022-07-10 18:58 UTC, youknowone approved these changes
The code changes look good! But maybe you didn't set your git email as your github email.
Do you want to change it before merge?

2022-07-13 11:04 UTC, youknowone commented
@zer0who please let me know if you don't care about email address. I don't mind to merge it as it is if you are ok.

2022-07-13 13:18 UTC, fanninpm commented
> @zer0who please let me know if you don't care about email address. I don't mind to merge it as it is if you are ok.

[Here is GitHub's documentation to set your commit email address.](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)

In order to fix these commits, you can run the following commands:

```text
git fetch upstream
git rebase --exec 'git commit --amend --reset-author' -i upstream/main
```

2022-07-13 15:48 UTC, zer0who commented
> @zer0who please let me know if you don't care about email address. I don't mind to merge it as it is if you are ok.

I don't know exatly that email you mentioned, but I did it as I understanded. Is it right?

2022-07-13 17:28 UTC, youknowone commented
check `git log` in your branch. the email of your commit is not your actual email.
(I don't think your email is `62321708+zer0hoo@users.noreply.github.com`)

2022-07-13 19:34 UTC, fanninpm commented
> > @zer0who please let me know if you don't care about email address. I don't mind to merge it as it is if you are ok.
> 
> [Here is GitHub's documentation to set your commit email address.](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address)
> 
> In order to fix these commits, you can run the following commands:
> 
> ```
> git fetch upstream
> git rebase --exec 'git commit --amend --reset-author' -i upstream/main
> ```

I forgot to add `git push --force` to that list.

2022-07-14 12:08 UTC, Snowapril commented
@zer0who Yeah It seems good now 😊

2022-07-14 12:39 UTC, fanninpm commented
> Am I right??

Here's how you can tell:

- On GitHub, you can look to see if your avatar is displayed next to each of your commits.
- Locally, running [`git log`](https://git-scm.com/docs/git-log) will tell you who authored a given commit. There will normally be a line that says `Author: Your Name <yourname@example.com>`. If the email address in that commit matches one that GitHub recognizes (e.g. the one linked to your GitHub account), then GitHub will display your avatar next to each of your commits.

2022-07-14 13:31 UTC, zer0who commented
> > Am I right??
> 
> Here's how you can tell:
> 
> * On GitHub, you can look to see if your avatar is displayed next to each of your commits.
> * Locally, running [`git log`](https://git-scm.com/docs/git-log) will tell you who authored a given commit. There will normally be a line that says `Author: Your Name <yourname@example.com>`. If the email address in that commit matches one that GitHub recognizes (e.g. the one linked to your GitHub account), then GitHub will display your avatar next to each of your commits.

Thank you so much :)

2022-07-14 13:32 UTC, merged