Implement Number protocol for PyComplex
RustPython/RustPython pull request #3838
Opened 2022-07-03 02:24 UTC by fanninpm

Implementation based on #3507.

2022-07-05 18:47 UTC, qingshi163 requested changes
Looks great for the implement

2022-07-05 18:47 UTC, qingshi163 commented on vm/src/builtins/complex.rs
> +        true_divide: Some(|number, other, vm| {
all of the function witch is None could be replaced by
```
..PyNumberMethods::NOT_IMPLEMENTED
```
at the end of the block

2022-07-09 00:41 UTC, Snowapril commented
I think Implementing missing `PySequenceMethods`, `PyMappingMethods`, `PyNumberMethods` for some types can be good first issue for first-comer. How do you think?

2022-07-09 12:27 UTC, youknowone approved these changes

2022-07-10 19:29 UTC, qingshi163 approved these changes
Great!

2022-07-10 19:30 UTC, merged