Update `_mut_iter_equal_skeleton` method
RustPython/RustPython pull request #3968
Opened 2022-07-25 13:08 UTC by TwoPair

This code is tested based on `list_tests.py::CommonTest::test_remove`,
except for lines `352~358` that seem related to `str` test.

2022-07-25 19:09 UTC, youknowone commented
line 352 is not related to string. try to print its type like `print(type(self.type2test))` that's list type. e.g. `list`.
`list('abcdefghcij')` is `['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'c', 'i', 'j']`

2022-07-25 19:11 UTC, youknowone commented
By watching CI, it is causing dead-lock. it didn't finish during 4 hours.

2022-07-27 17:39 UTC, TwoPair commented
Now, two list method `index`, `remove` works normally by fixing `_mut_iter_equal_skeleton` method.

2022-07-27 21:18 UTC, Snowapril commented on vm/src/sequence.rs
>                  if eq {
```suggestion
                let elem = elem.clone();
                drop(guard);
                
                if elem.rich_compare_bool(needle, PyComparisonOp::Eq, vm)? {
```

2022-07-27 21:18 UTC, Snowapril commented
Nice catch! The changed codes seem totally fine to me. Please check unexpected success in `test_list`, `test_deque` tests.

2022-07-29 12:25 UTC, fanninpm requested changes
Please don't leave these things behind in the code. They're not there in CPython.

2022-07-29 12:25 UTC, fanninpm commented on Lib/test/test_list.py
```suggestion
```

2022-07-29 12:25 UTC, fanninpm commented on Lib/test/test_list.py
```suggestion
```

2022-08-01 12:42 UTC, fanninpm reviewed
LGTM.

2022-08-02 08:25 UTC, youknowone commented
@qingshi163 could you review this PR?

2022-08-03 08:56 UTC, qingshi163 commented
As I remember, the guard or borrower is to optimize the compare by check if the class is not the heap type, so we can reuse the compare function in each loop. Also to use rich_compare_bool we cannot reuse the PyTypeRef for the compared object but this will be no more the issue if we can fetch the PyType atomicly in the future.

Yes, the correctness is more important than performance, but if you can solve the problem without drawback the performance could be amazing. if not please advise the issue or the failing point of the current implement, so we could see why this is not going to work.

@youknowone 

Thanks

2022-08-07 06:56 UTC, youknowone approved these changes
@qingshi163 I created an issue to refer this pr #4008
@TwoPair Thank you!

2022-08-07 06:57 UTC, merged