<code object>::replace()
RustPython/RustPython pull request #4207
Opened 2022-10-09 17:47 UTC by dannasman

Hello there!

I started working on issue #4022  and was just wondering whether this is the right place to implement the replace() function.

2022-10-10 07:59 UTC, youknowone commented
Yes, exactly!

2022-10-10 18:21 UTC, dannasman commented
Should I wrap the function parameters with `OptionalArg`? There is quite a lot of optional parameters.  Also what should the parameter types be. For example if you want to replace `flags` field of the code object should the parameter passed to `replace()` be `OptionalArg<u16>` or `OptionalArg<CodeFlags>`?

2022-10-11 06:09 UTC, youknowone commented
You'd better to check `#[derive(FromArgs)]`. `OptionalArg` in function signature only supports optional positional args, but you need optional keyword args.
I prefer `CodeFlags` to `u16` when possible. RustPython automatically can make additional check during its conversion.

2022-10-11 15:19 UTC, dannasman commented
I managed to implement the method so that it passes `test_replace` in `test_code.py` for all 10 attributes that have a `#[pygetset]` function in `code.rs` (rest I commented out for the duration of testing).

2022-10-14 03:21 UTC, youknowone requested changes
other parts looks good, thank you!

2022-10-14 03:21 UTC, youknowone commented on vm/src/builtins/code.rs
> +    #[pyarg(any, optional)]
```suggestion
    #[pyarg(named, optional)]
```
for every lines. because it doesn't take positional argument

2022-10-15 05:10 UTC, youknowone approved these changes
Great! Thank you for contributing!

2022-10-15 05:10 UTC, merged

2022-10-15 06:27 UTC, dannasman commented
Thank you for the guidance!