Allow log2() to work on large integers
RustPython/RustPython pull request #4241
Opened 2022-10-22 21:59 UTC by devonhollowood

Part of #1671

My plan is to extend this to log() and log10() in the next PR — I wanted to see how you felt about the approach, first. Let me know what you think.

2022-10-23 00:10 UTC, devonhollowood commented
It looks like the error is in `test_statistics.py`:

```
UNEXPECTED SUCCESS: test_regression_25177 (__main__.TestMean)
```

However, I'm not sure why this is suddenly passing, so I'm a little hesitant to remove the `@unittest.expectedFailure`. What do you think?

2022-10-23 04:33 UTC, youknowone requested changes
Great! I left a naming style request.

Yes, removing the decorator is correct way. Maybe it was using log2 somewhere and you caught it.

2022-10-23 04:33 UTC, youknowone commented on stdlib/src/math.rs
> +    fn ilog2(x: &BigInt) -> f64 {
```suggestion
    fn int_log2(x: &BigInt) -> f64 {
```

2022-10-23 17:18 UTC, devonhollowood commented on stdlib/src/math.rs
> +    fn ilog2(x: &BigInt) -> f64 {
Done and done!

2022-10-24 14:45 UTC, youknowone approved these changes
Thank you for contributing!

2022-10-24 14:45 UTC, merged