Implement `array.array.__contains__`
RustPython/RustPython pull request #4466
Opened 2023-01-22 08:15 UTC by moreal

CPython implements `array.__contains__` but RustPython doesn't implement it yet. This pull request implements it.

## CPython

```python
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> array.array('B').__contains__
<method-wrapper '__contains__' of array.array object at 0x1051ce700>
```

## RustPython (before)

```python
Welcome to the magnificent Rust Python 0.2.0 interpreter 😱 🖖
>>>>> import array
>>>>> array.array('B').__contains__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'array' object has no attribute '__contains__'
```

## RustPython (after)

```python
Welcome to the magnificent Rust Python 0.2.0 interpreter 😱 🖖
>>>>> import array
>>>>> array.array('B').__contains__
<bound method array.__contains__ of array('B')>
```

2023-01-22 09:37 UTC, moreal commented
I'm not sure why [running tests in macOS is failing](https://github.com/RustPython/RustPython/actions/runs/3978965699/jobs/6821084358) but others succeed. So I open this pull request as ready for review.

2023-01-22 11:48 UTC, youknowone commented
The faling tests is looking unrelated

2023-01-22 12:28 UTC, youknowone requested changes
Thank you! I left a suggestion for double expect.

2023-01-22 13:11 UTC, DimitrisJim commented on stdlib/src/array.rs
> +                    .expect("Expected to be checked by array.len() and read lock.")
`ArrayContentType` also has an `iter` which can be used here instead, i.e `for element in array.iter().map(|e| e.expect(...))`

2023-01-22 13:46 UTC, moreal commented on stdlib/src/array.rs
> +                    .expect("Expected to be checked by array.len() and read lock.")
I applied this suggestion as `for element in array.iter().map(|e| e.expect(...))` way.

2023-01-22 14:44 UTC, DimitrisJim commented
lgtm. do you think you could test this a bit in `extra_tests/stdlib_array.py`? Its weird that no test functions in `test_array` seem to check it.

2023-01-22 15:18 UTC, moreal commented
> lgtm. do you think you could test this a bit in `extra_tests/stdlib_array.py`? A couple of `in` calls should do the trick, its weird that no test functions in `test_array` seem to check it.

There is `test_array.NumberTest.test_iterationcontains` test to test `[element] in [array]`. And about the `in` expression how works:

> https://docs.python.org/3/reference/expressions.html#not-in
> For user-defined classes which define the __contains__() method, x in y returns True if y.__contains__(x) returns a true value, and False otherwise.
> 
> For user-defined classes which do not define __contains__() but do define __iter__(), x in y is True if some value z, for which the expression x is z or x == z is true, is produced while iterating over y. If an exception is raised dur[in](https://docs.python.org/3/reference/expressions.html#in)g the iteration, it is as if in raised that exception.

So.. I think the `test_iterationcontains` test is enough.

2023-01-23 14:45 UTC, DimitrisJim approved these changes
> There is test_array.NumberTest.test_iterationcontains test to test [element] in [array]. And about the in expression how works

Ah, I missed that! Either way, thanks for adding some manually to `stdlib_array`

2023-01-23 14:46 UTC, merged