Pathconf names
RustPython/RustPython pull request #4508
Opened 2023-02-16 01:10 UTC by marvinmednick

Implementation for os.pathconf_names  resolves #4494

2023-02-16 01:47 UTC, marvinmednick commented
Let me know if I did something incorrectly -- I see as part my pull requesets commits authored by others....   The two changes I'm looking to pull in for pathconf_names are https://github.com/RustPython/RustPython/pull/4508/commits/d8fe7787bf9690d86bb7c57885d7fa0b0f1fb8be and https://github.com/RustPython/RustPython/pull/4508/commits/df482663717dd84b570cb7e7e0007f3b8ede021b

2023-02-16 02:06 UTC, fanninpm commented
After CI completes, feel free to do a `git rebase ...` followed by a `git push --force`.

2023-02-17 12:32 UTC, youknowone commented
I rebased it. `git rebase` is very useful tool to send patches.
https://docs.gitlab.com/ee/topics/git/git_rebase.html

2023-02-17 13:08 UTC, youknowone requested changes

2023-02-17 13:08 UTC, youknowone commented on extra_tests/snippets/stdlib_os.py
> +if "win" not in sys.platform:
```suggestion
if not sys.platform.startswith("win"):
```
"darwin" also contains "win", which means macOS.

2023-02-17 13:08 UTC, youknowone commented on vm/src/stdlib/posix.rs
> +            let key: PyObjectRef = vm.ctx.new_str(variant.to_string()).into();
```suggestion
            let key = vm.ctx.new_str(variant.to_string());
```
`PyStrRef` itself is dict key compatible.

2023-02-18 20:52 UTC, marvinmednick commented
> I rebased it. `git rebase` is very useful tool to send patches. https://docs.gitlab.com/ee/topics/git/git_rebase.html

Thanks -- I was looking at trying to do that but it didn't seem to look right as I still ended up with 2 additional changes -- I was thinking my baseline wasn't quite right or I did something incorrectly.

2023-02-20 05:01 UTC, marvinmednick commented
I'm looking at the error --    I found an online free online macos simlulator and was able to get the error 22 manually trying the command os.pathconf('/',21)   but that isn't conclusive.   (pathconf worked for indexes 0-20).   
I'd like to check the the PathconfVar entries for darwin...   but darwin doesn't seem to be a confguration check within PathconfVar    

It looks like there are some platforms which may have pathconf indexes that are greater then 20  (e.g.  in libc  
libc:   src/unix/haiku/mod.rs:pub const _PC_REC_MAX_XFER_SIZE: ::c_int = 32;
though on linux the same parameter is index 15.
libc    src/unix/linux_like/linux/mod.rs:pub const _PC_REC_MAX_XFER_SIZE: ::c_int = 15;

I suppose this is more a of libc specfic question does anyone know how can I tell which of the libc flavor will be used on macos/darwin? (and therefore which pathconf indexes value will show up in PathconfVar)

2023-02-21 10:31 UTC, youknowone approved these changes
You don't need to fix every macOS issue if if you don't have macOS machine. Please fill free to ask help if you have hard trouble to fix.

I think adding it only for linux is a working option. I made a change. We can fix macOS issue later.

Thank you for contributing!

2023-02-21 10:31 UTC, youknowone commented on vm/src/stdlib/posix.rs
> +    // TODO: this is expected to be run on macOS as a unix, but somehow not.
I put linux cfg until it is fixed for macos

2023-02-21 15:03 UTC, merged

2023-02-21 15:04 UTC, youknowone commented
Thank you for contributing!