Fix #4588
RustPython/RustPython pull request #4711
Opened 2023-03-18 04:44 UTC by minhrongcon2000

Fix #4588

2023-03-18 08:13 UTC, youknowone commented
would you remove `skip` from the test and add test case commit from #4593 to ensure it is fixed?

2023-03-18 08:18 UTC, minhrongcon2000 commented
It will still fail because I didn't integrate locale into format integer with numeric option... But if you want to remove it to test whether it is panic, I will do it!

2023-03-18 08:54 UTC, youknowone commented
you can replace `skip` to `expectedFailure` in that case. At least we can test if it is crash or not.

2023-03-18 13:11 UTC, youknowone commented on Lib/test/test_format.py
> +            x = x // 10
we don't add our original tests under `Lib/`. Could you move this test under `extra_tests/snippets/`?

2023-03-18 15:36 UTC, youknowone commented on Lib/test/test_format.py
> -
this is not intended change, right?

2023-03-18 15:37 UTC, minhrongcon2000 commented on Lib/test/test_format.py
> -
Yeah! This is not intended

2023-03-18 15:39 UTC, youknowone commented on extra_tests/snippets/test_issue_4588.py
> +    format(x, ',')
this is test for `format`. `builtin_format.py` covers tests about it.

2023-03-20 08:06 UTC, youknowone requested changes

2023-03-20 08:06 UTC, youknowone commented on Lib/test/test_format.py
> -
please also revert this line too

2023-03-21 05:38 UTC, youknowone approved these changes
Thank you!

2023-03-21 05:40 UTC, youknowone commented
rerunning CI with #4593

2023-03-21 06:09 UTC, youknowone commented
Could you check the test result? new code seems generating malformatted string.

```
---- format::tests::test_format_int_sep stdout ----
thread 'format::tests::test_format_int_sep' panicked at 'assertion failed: `(left == right)`
  left: `Ok("0000001234567,890,123,456,789,012,345,678")`,
 right: `Ok("1,234,567,890,123,456,789,012,345,678")`', common/src/format.rs:1035:9
```

2023-03-23 07:38 UTC, youknowone approved these changes
Thanks!

2023-03-23 07:38 UTC, merged