update test_ordered_dict.py from cpython 3.11.2
RustPython/RustPython pull request #4775
Opened 2023-03-26 02:16 UTC by Brain-organizer

update test_ordered_dict.py from cpython 3.11.2

2023-03-26 02:30 UTC, fanninpm requested changes

2023-03-26 02:30 UTC, fanninpm commented on Lib/test/test_ordered_dict.py
> +    @unittest.expectedFailure
Please break this out into a separate commit.

2023-03-26 02:30 UTC, fanninpm commented on Lib/test/test_ordered_dict.py
> +    @unittest.expectedFailure
Please break this out into a separate commit.

2023-03-27 19:06 UTC, DimitrisJim commented
Thanks! The results have some failures and some successes. Failures:

```
test.test_ordered_dict.CSimpleLRUCacheTests.test_pop
test.test_ordered_dict.PySimpleLRUCacheTests.test_pop
```

and the unexpected successes:

```
test.test_ordered_dict.CPythonOrderedDictSubclassTests.test_copying
test.test_ordered_dict.CPythonOrderedDictSubclassTests.test_pop
test.test_ordered_dict.CPythonOrderedDictTests.test_copying
test.test_ordered_dict.CPythonOrderedDictTests.test_pop
test.test_ordered_dict.PurePythonOrderedDictSubclassTests.test_copying
test.test_ordered_dict.PurePythonOrderedDictSubclassTests.test_pop
test.test_ordered_dict.PurePythonOrderedDictTests.test_copying
test.test_ordered_dict.PurePythonOrderedDictTests.test_pop
```

2023-04-12 17:36 UTC, DimitrisJim commented
Superseded by https://github.com/RustPython/RustPython/pull/4846, thanks for opening the PR though!

2023-04-12 17:36 UTC, closed without merging