Implemented tp_repr slots for more types
RustPython/RustPython pull request #4849
Opened 2023-04-04 14:47 UTC by haxelion

I implemented the tp_repr slot for most types except tuples.
Implementing it for tuples turns out to be quite tricky and will probably require quite some refactoring.

2023-04-05 00:47 UTC, haxelion commented
Ah it seems I missed the WASM specific types. Let me fix this later.

2023-04-05 08:03 UTC, youknowone approved these changes
Thank you! The failing test looks unrelated.

2023-04-05 08:03 UTC, youknowone requested changes
sorry, approve was mistake

2023-04-06 01:12 UTC, haxelion commented on vm/src/stdlib/io.rs
> -        #[pymethod(magic)]
Let me check if I can get it working.
I have a similar problem with the trait for tuple so it might be helpful.

2023-04-06 14:02 UTC, youknowone commented on vm/src/stdlib/io.rs
> -        #[pymethod(magic)]
Idea: The Representable trait eventually implement `#[slot] fn slot_repr`. The same slot can be filled in same way in this mixin trait.

2023-04-20 07:06 UTC, youknowone approved these changes
Thank you for contributing!
I finished my own suggestions to reduce conflict with other patches.

2023-04-20 12:02 UTC, merged