Raise error on power with negative number
RustPython/RustPython pull request #5143
Opened 2023-12-28 16:33 UTC by kennysliding

Addressing issue #5138, this PR adds another check on the `inner_pow` function to raise error when the real number part of power number is negative

2023-12-30 04:17 UTC, youknowone commented
Could you rebase it to upstream main? #5144 resolved the unrelated clippy errors.

2023-12-30 04:45 UTC, kennysliding commented
> Could you rebase it to upstream main?

Just did

2024-01-11 06:52 UTC, youknowone requested changes
Thank you for contributing! Because you fixed the bug, you can remove `@unittest.expectedFailure` from the related test.

2024-01-12 12:16 UTC, youknowone approved these changes
👍

2024-01-12 12:16 UTC, merged

2024-01-13 14:44 UTC, kennysliding commented
@youknowone Thanks! I'm up for taking up other PRs in the future too.