Deprecation warning fix
RustPython/RustPython pull request #5152
Opened 2024-01-21 14:03 UTC by alinioan

Fixed case where returning strict subclasses of complex in complex doesn't give a deprecation warning.

2024-01-22 07:27 UTC, youknowone requested changes
The change looks good, thank you! Could you check the rustfmt issue? In high chance, it will be fixed by simply running `cargo fmt --all`

2024-01-22 14:43 UTC, alinioan commented
I ran the cargo fmt --all comand and made another comit. I hope that fixes the issue

2024-01-22 14:46 UTC, alexandruradovici requested changes

2024-01-22 14:46 UTC, alexandruradovici commented on vm/src/builtins/complex.rs
> +                return Ok(Some((ret.value, true)));
```suggestion
                Ok(Some((ret.value, true)))
```

2024-01-22 14:46 UTC, alexandruradovici commented on vm/src/builtins/complex.rs
> +                };
```suggestion
                match result.payload::<PyComplex>() {
                    Some(complex_obj) => Ok(Some((complex_obj.value, true))),
                    None => Err(vm.new_type_error(format!(
                        "__complex__ returned non-complex (type '{}')",
                        result.class().name()
                    ))),
                }
```

2024-01-23 11:58 UTC, alexandruradovici requested changes
Please fix the conflicts or rebase this.

2024-01-23 15:50 UTC, alexandruradovici requested changes
Two small changes due to my mistake.

2024-01-23 15:50 UTC, alexandruradovici commented on vm/src/builtins/complex.rs
> +                }
```suggestion
                return match result.payload::<PyComplex>() {
                    Some(complex_obj) => Ok(Some((complex_obj.value, true))),
                    None => Err(vm.new_type_error(format!(
                        "__complex__ returned non-complex (type '{}')",
                        result.class().name()
                    ))),
                };
```

My mistake here, it thought it was the last line in the function.

2024-01-23 15:50 UTC, alexandruradovici commented on vm/src/builtins/complex.rs
> +                Ok(Some((ret.value, true)))
```suggestion
                return Ok(Some((ret.value, true)));
```

My mistake here, it thought it was the last line in the function.

2024-01-23 17:10 UTC, youknowone commented
If you are interested in making commits cleaner, `git rebase` is a good friend for open source contributors.
I am ok with it because I can squash it, but you may want to try for a practice.

2024-01-24 08:56 UTC, youknowone commented on vm/src/builtins/complex.rs
> +                return Ok(Some((ret.value, true)))
```suggestion
                return Ok(Some((ret.value, true)));
```

2024-01-25 05:53 UTC, youknowone approved these changes
Thank you for contributing!

2024-01-25 05:54 UTC, merged